import Head from "next/head"
import Header from "@/components/Header"
import rogueImg from "../public/images/Characters/Overworld_Rogue.png"
import rogueHunter from "../public/images/Characters/roguehunte.png"
import overLogo from "../public/images/Logo/Overworld_Logotype_Red.png"
import blindImg from "../public/images/Characters/blind.png"
import Image from "next/image"

export default function Home() {
  return (
    <>
      <Head>
        <title>Overtwemes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="relative container mx-auto md:px-6 pt-6 flex justify-center items-center h-screen">
        <div className="relative w-full">
          <div className="hidden md:block absolute w-full container mx-auto top-[50%] left-[50%] -translate-y-1/2 -translate-x-1/2">
            <Image className="h-[255px]" src={overLogo} alt="overworld" />
          </div>
          <div className="relative flex justify-center items-center md:justify-end">
            <Image
              className="w-full md:hidden bottom-0 transform h-screen object-cover object-center"
              src={rogueImg}
              alt="character male"
              height={550}
            />
            <Image
              className="hidden md:flex object-cover object-center"
              src={rogueHunter}
              alt="rogue and huntress"
            />
            <div className="md:hidden absolute top-[50%] left-[50%] -translate-y-1/2 -translate-x-1/2">
              <button className="bg-btnBg px-4 py-2 text-slate-50 rounded-lg font-medium">
                VERIFY TWITTER
              </button>
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 pl-1 lg:pl-4 xl:pl-0">
          <Image
            className="w-[60px] lg:w-[100px]"
            src={blindImg}
            alt="overworld little blind character"
            width={100}
          />
        </div>
      </main>
    </>
  )
}
